# Generated by Django 4.2.7 on 2023-11-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('food', '0001_initial'),
        ('users', '0002_remove_student_food_remove_student_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='food',
            field=models.ManyToManyField(to='food.food'),
        ),
        migrations.AddField(
            model_name='student',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
