# Generated by Django 4.2.7 on 2023-11-25 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_student_food_student_number_alter_student_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='food',
        ),
    ]
