# Generated by Django 4.2.7 on 2023-11-25 09:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_id_student_student_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='student_id',
            new_name='id',
        ),
    ]
